package edu.eci.cosw.jpa.sample.model;
// Generated Mar 9, 2016 7:01:57 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Pacientes generated by hbm2java
 */
@Entity
@Table(name = "PACIENTES")
public class Paciente implements java.io.Serializable {


    @EmbeddedId    
    @Column(name = "id")
    private PacienteId id;

    @Column(name = "nombre")
    private String nombre;

    @Column(name = "fecha_nacimiento")
    private Date fechaNacimiento;

    @OneToMany(cascade = CascadeType.ALL, orphanRemoval=true)
    //@OneToMany(cascade = CascadeType.ALL)
    @JoinColumns({
        @JoinColumn(name="PACIENTES_id", referencedColumnName="id", nullable=false),
        @JoinColumn(name="PACIENTES_tipo_id", referencedColumnName="tipo_id", nullable=false)
    })
    private Set<Consulta> consultas = new HashSet<>(0);

    public Paciente() {
    }

    public Paciente(PacienteId id, String nombre, Date fechaNacimiento) {
        this.id = id;
        this.nombre = nombre;
        this.fechaNacimiento = fechaNacimiento;
    }

    public Paciente(PacienteId id, String nombre, Date fechaNacimiento, Set<Consulta> consultas) {
        this.id = id;
        this.nombre = nombre;
        this.fechaNacimiento = fechaNacimiento;
        this.consultas = consultas;
    }

    
  
    public PacienteId getId() {
        return this.id;
    }

    public void setId(PacienteId id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }

    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }


    public Set<Consulta> getConsultas() {
        return this.consultas;
    }

    public void setConsultas(Set<Consulta> consultases) {
        this.consultas = consultases;
    }

    public void addConsulta(Consulta consulta){ this.consultas.add(consulta); }

}
