package edu.eci.cosw.jpa.sample.model;
// Generated Mar 9, 2016 7:01:57 AM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.Date;

/**
 * PolizasAprobadas generated by hbm2java
 */
@Entity
@Table(name = "POLIZAS_APROVADAS")
public class PolizaAprobada implements java.io.Serializable {

    @EmbeddedId
    @Column(name="id")
    private PolizaAprobadaId id;

    @ManyToOne(cascade = CascadeType.ALL)
    @JoinColumns({
            @JoinColumn(referencedColumnName="id", nullable=false),
            @JoinColumn(referencedColumnName="tipo_id", nullable=false)
    })
    private Cliente clientes;


    @ManyToOne(cascade = CascadeType.ALL)
    @JoinColumns({
            @JoinColumn( referencedColumnName="codigo_poliza", nullable=false)
    })

    private TipoPoliza tiposPoliza;

    @Column(name = "fecha_aprobacion")
    private Date fechaAprobacion;

    @Column(name = "fecha_vencimiento")
    private Date fechaVencimiento;

    public PolizaAprobada() {
    }

    public PolizaAprobada(PolizaAprobadaId id, Cliente clientes, TipoPoliza tiposPoliza, Date fechaAprobacion, Date fechaVencimiento) {
        this.id = id;
        this.clientes = clientes;
        this.tiposPoliza = tiposPoliza;
        this.fechaAprobacion = fechaAprobacion;
        this.fechaVencimiento = fechaVencimiento;
    }

    public PolizaAprobadaId getId() {
        return this.id;
    }

    public void setId(PolizaAprobadaId id) {
        this.id = id;
    }

    public Cliente getClientes() {
        return this.clientes;
    }

    public void setClientes(Cliente clientes) {
        this.clientes = clientes;
    }

    public TipoPoliza getTiposPoliza() {
        return this.tiposPoliza;
    }

    public void setTiposPoliza(TipoPoliza tiposPoliza) {
        this.tiposPoliza = tiposPoliza;
    }

    public Date getFechaAprobacion() {
        return this.fechaAprobacion;
    }

    public void setFechaAprobacion(Date fechaAprobacion) {
        this.fechaAprobacion = fechaAprobacion;
    }

    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }

    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }


}


